[[s]]
id = "start"
title = "Привет, меня зовут БОТ."
start_qid = "как зовут?"

[[q]]
id = "как зовут?"
param_name = "имя"
texts = ["А как тебя зовут?"]
next_qid = "есть мечта?"

[[q]]
id = "есть мечта?"
texts = [
    "{{ .имя }} у Вас есть мечта?",
]
    [[q.opts]]
    key = "Да"
    qid = "да - есть мечта"
    [[q.opts]]
    key = "Нет"
    qid = "нет - нет мечты"
param_name = "мечта"
next_qid = "end"